### ISSUE TITLE
Output Visualization

### ISSUE THREAD

**Issue by airplane-glitch** [mitre-public/open-aria#53]
The current output, such as "scaryTrackOutput.json", contains highly valuable information about detected aircraft conflicts. However, I would like to request visualization capabilities for these detected events. This would allow for better conflict assessment by providing a graphical representation of the data. Instead of relying solely on raw JSON outputs, visualizing these events would enable more efficient interpretation, pattern recognition, and decision-making.

**Comment by politeRaccoon** [comment]
Hello @airplane-glitch
  Thank you for looking into the project.  I appreciate it.  Also, this is a good idea.  

   There should be a way to integrate [this work](https://github.com/mitre-public/commons/blob/main/docs/mapping.md) to build maps of individual events.   We'd also need to add a "configuration toggle" for this behavior.  

  All-in-all, this is a reasonable ask.  I'll work on this this week.

**Comment by politeRaccoon** [comment]
The `MapSink` was added in commit: e1d8af832851c0531302a14e09b8d5d13a57bc63

You can use a MapSink by adding this to your configuration:

```
      - pluginClass: "org.mitre.openaria.airborne.config.MapSinkSupplier"
        configOptions:
          eventDirectory: "eventMaps"
          useMapBox: false
          mapWidthInNauticalMiles: 15.0
```

An example configuration that uses a MapSink is [here](https://github.com/mitre-public/open-aria/blob/main/open-aria-airborne/src/test/resources/sampleConfig.yaml)

Thank you again for filing the issue/feature request. Happy to hear feedback on the new feature.
